MERGE INTO GENRE (GENRE_ID, NAME) VALUES (1, 'Комедия');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (2, 'Драма');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (3, 'Мультфильм');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (4, 'Триллер');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (5, 'Документальный');
MERGE INTO GENRE (GENRE_ID, NAME) VALUES (6, 'Боевик');

MERGE INTO RATING_MPA (RATING_MPA_ID, NAME, DESCRIPTION)
VALUES (1, 'G', 'No age restrictions');

MERGE INTO RATING_MPA (RATING_MPA_ID, NAME, DESCRIPTION)
VALUES (2, 'PG', 'Parental guidance suggested');

MERGE INTO RATING_MPA (RATING_MPA_ID, NAME, DESCRIPTION)
VALUES (3, 'PG-13', 'Not recommended for children under 13');

MERGE INTO RATING_MPA (RATING_MPA_ID, NAME, DESCRIPTION)
VALUES (4, 'R', 'Restricted: under 17 requires accompanying parent or adult guardian');

MERGE INTO RATING_MPA (RATING_MPA_ID, NAME, DESCRIPTION)
VALUES (5, 'NC-17', 'No one 17 and under admitted');
